### ISSUE TITLE
Subscription "Get" link defaults to https://www.twitch.tv/products/<username>

### ISSUE THREAD

**Issue by djerelle** [freaktechnik/twitch-emotes-extension#22]
I assume that's how you have it set up; the twitch products page doesn't update to your new username if you've changed it after setting up affiliation.

Ex if my old username when I affiliated was Djerelle but I changed it to TheDinDjerelle, my products page will still be https://www.twitch.tv/products/djerelle

I guess the easiest way would be to have an override option.
Other than that, love the extension! Only one I use

**Comment by freaktechnik** [comment]
I'm aware of this issue and hope to push a fix for it soon.

**Comment by freaktechnik** [comment]
Hi, this issue is fixed in the latest released version. You can override the username used for the product link in the settings. The source for that version is not yet published on here.
