### ISSUE TITLE
FFZ emotes not showing

### ISSUE THREAD

**Issue by amphyvi** [freaktechnik/twitch-emotes-extension#23]
Hi!  BTTV emotes are showing within this extension for me, but not FFZ emotes:

https://www.frankerfacez.com/channel/kbbles

Is this related to the fact that I changed my username on Twitch a couple years ago, after starting with FFZ?  What can be done to fix this?

Thanks in advance!

**Comment by freaktechnik** [comment]
![image](https://user-images.githubusercontent.com/640949/59469915-6d060500-8e36-11e9-9afe-8222e2eaacc2.png)

Appears to be working for me.
